---
- name: AMC Report Writer
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    db: /opt/amc-reports/database/amc_reports.db

  tasks:

    - name: Create new report run
      shell: |
        sqlite3 {{ db }} \
        "INSERT INTO report_runs(workflow_name,status)
         VALUES('Daily Windows Infrastructure Health Check','Running');"

    - name: Display latest report run
      shell: |
        sqlite3 {{ db }} \
        "SELECT * FROM report_runs ORDER BY id DESC LIMIT 1;"
      register: report

    - name: Show report
      debug:
        var: report.stdout
