---
- name: Windows Information
  hosts: windows
  gather_facts: no

  tasks:

    - name: Hostname
      ansible.windows.win_command: hostname
      register: host

    - debug:
        var: host.stdout

    - name: OS Name
      ansible.windows.win_shell: |
        (Get-CimInstance Win32_OperatingSystem).Caption
      register: os

    - debug:
        var: os.stdout

    - name: Domain
      ansible.windows.win_shell: |
        (Get-WmiObject Win32_ComputerSystem).Domain
      register: domain

    - debug:
        var: domain.stdout

    - name: Total RAM
      ansible.windows.win_shell: |
        [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory/1GB,2)
      register: ram

    - debug:
        var: ram.stdout

    - name: IP Addresses
      ansible.windows.win_shell: |
        (Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object {$_.IPAddress -notlike "169.*"}).IPAddress
      register: ips

    - debug:
        var: ips.stdout_lines
