---
- name: Check Reboot Requirement
  hosts: windows
  gather_facts: no

  tasks:

    - name: Check if reboot is required
      ansible.windows.win_shell: |
        if (
            Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending" `
            -or
            Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired"
        )
        {
            "REBOOT REQUIRED"
        }
        else
        {
            "NO REBOOT REQUIRED"
        }
      register: reboot_status

    - name: Display reboot status
      debug:
        var: reboot_status.stdout
