---
- name: Active Directory Replication Health
  hosts: windows
  gather_facts: no

  tasks:

    - name: Check AD Replication
      ansible.windows.win_shell: |
        repadmin /replsummary
      register: replication

    - name: Display Replication Summary
      debug:
        var: replication.stdout_lines
