---
- name: Windows Administrators Audit
  hosts: windows
  gather_facts: no

  tasks:

    - name: Get Administrators
      ansible.windows.win_shell: |

        $cs = Get-CimInstance Win32_ComputerSystem

        if ($cs.DomainRole -ge 4)
        {
            Write-Host "===== DOMAIN CONTROLLER ====="

            Get-ADGroupMember "Domain Admins" |
            Select Name,ObjectClass |
            ConvertTo-Json
        }
        else
        {
            Write-Host "===== MEMBER SERVER ====="

            Get-LocalGroupMember Administrators |
            Select Name,ObjectClass |
            ConvertTo-Json
        }

      register: admins

    - debug:
        var: admins.stdout
