---
- name: Disk Space Report
  hosts: windows
  gather_facts: no

  tasks:

    - name: Get disk information
      ansible.windows.win_shell: |
        Get-CimInstance Win32_LogicalDisk |
        Where-Object {
            $_.DriveType -eq 3 -and $_.Size -gt 0
        } |
        Select-Object DeviceID,
          @{Name="SizeGB";Expression={[math]::Round($_.Size/1GB,2)}},
          @{Name="FreeGB";Expression={[math]::Round($_.FreeSpace/1GB,2)}},
          @{Name="UsedGB";Expression={[math]::Round(($_.Size-$_.FreeSpace)/1GB,2)}},
          @{Name="FreePercent";Expression={[math]::Round(($_.FreeSpace/$_.Size)*100,2)}} |
        ConvertTo-Json
      register: diskinfo

    - name: Display disk information
      debug:
        var: diskinfo.stdout
