---
- name: Test Windows Connectivity
  hosts: windows
  gather_facts: no

  tasks:

    - name: Ping Windows hosts
      ansible.windows.win_ping:
      register: ping_result

    - name: Show ping result
      debug:
        var: ping_result.ping
